[package]
name = "example-image-classification"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
image = "0.24"
ndarray = "0.15"
reqwest = "0.11"
safetensors = "0.4"
safetensors-ndarray = { path = "../../../../../lib/safetensors-ndarray" }
tokio.workspace = true
common = { path = "../common" }
