[package]
name = "lightning-schema"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde.workspace = true
anyhow.workspace = true
fleek-crypto.workspace = true
ink-quill.workspace = true
lightning-types.workspace = true
bytes = "1.5"
arrayref = "0.3"
flexbuffers = "2.0"
