#!/bin/bash
set -eou pipefail
script_dir="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

# Force rebuild ort-sys for onnxruntime so that it's always available even when using cached
# depenedencies in CI and Docker.
# This causes https://github.com/pykeio/ort/blob/main/ort-sys/build.rs to always re-run.
if [ -n "${CI:-}" ]; then
    cargo clean -p ort-sys
    cargo build -p ort-sys
fi

# Build workspace packages
cargo build "$@"
