[package]
name = "fleek-service-fetcher"
version = "0.0.1"
edition.workspace = true
publish = false

[dependencies]
fn-sdk = { path = "../../lib/sdk" }
tokio.workspace = true
bytes.workspace = true
anyhow.workspace = true
tracing.workspace = true
arrayref = "0.3.7"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
url = "2.5.0"
cid = "0.11"
hex = "0.4"
workspace-hack = { version = "0.1", path = "../../etc/workspace-hack" }

[dev-dependencies]
lightning-schema = { path = "../../core/schema" }

[[bin]]
name = "fn-service-0"
path = "src/bin.rs"
