[package]
name = "lightning-syncronizer"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lightning-interfaces = { path = "../interfaces" }
lightning-utils = { path = "../utils" }
lightning-metrics = { path = "../metrics" }
lightning-rpc = { path = "../rpc" }
futures.workspace = true
anyhow.workspace = true
tracing.workspace = true
reqwest.workspace = true
serde_json.workspace = true
serde.workspace = true
humantime-serde.workspace = true
tokio.workspace = true
rand.workspace = true
fleek-crypto.workspace = true
async-channel = "2.2"
