[package]
name = "lightning-ebpf-programs"
version = "0.0.0"
edition = "2021"
authors = ["M. Meier <miguel@fleek.xyz>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aya-ebpf = { git = "https://github.com/aya-rs/aya", rev = "e5d107d" }
aya-log-ebpf = { git = "https://github.com/aya-rs/aya", rev = "e5d107d" }
lightning-ebpf-common = { path = "../common" }
memoffset = "0.9"
network-types = "0.0.5"

[build-dependencies]
aya-tool = { git = "https://github.com/aya-rs/aya", rev = "e5d107d" }

[profile.dev]
opt-level = 3
debug = false
# Removing this field causes BPF_PROG_LOAD syscall to fail.
# `Verifier output: last insn is not an exit or jmp.`
debug-assertions = false
overflow-checks = false
lto = true
panic = "abort"
incremental = false
codegen-units = 1
rpath = false

[profile.release]
lto = true
panic = "abort"
codegen-units = 1
