#!/bin/bash
set -eou pipefail
script_dir="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

# Install dependencies and prepare environment
. "${script_dir}"/prepare

# Define cargo fmt function
function cargo_fmt() {
    cargo fmt --all "$@"
}

# Run cargo fmt on workspace crates
echo "Running cargo fmt on workspace..."
cargo_fmt "$@"

# Get list of workspace members
workspace_members=($(cargo metadata --format-version=1 --no-deps | jq -r '.packages[] | select(.source == null) | .manifest_path | rtrimstr("/Cargo.toml")'))

# Look through all directories recursively and run clippy on them, not including the root
# directory or known workspace members.
eval find . -type d -mindepth 1 | while read dir; do
    if [[ " ${workspace_members[@]} " =~ " $(realpath ${dir}) " ]]; then
        continue
    fi

    (
        cd "$dir"

        if [ -f Cargo.toml ]; then
            echo "Running cargo fmt on $dir..."
            cargo_fmt
        fi
    )
done
