[package]
name = "fleek-service-js-poc"
version = "0.0.1"
edition.workspace = true

[dependencies]
fn-sdk = { path = "../../lib/sdk" }
blake3-tree = { path = "../../lib/blake3-tree" }
tokio.workspace = true
bytes.workspace = true
anyhow.workspace = true
tracing.workspace = true
fleek-crypto.workspace = true
arrayref = "0.3"
triomphe = "0.1"
serde.workspace = true
serde_json.workspace = true
hex = "0.4"
cid = "0.11"
urlencoding = "2.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Deno core + webapi extensions
deno_core = "0.301"
deno_webidl = "0.164"
deno_console = "0.164"
deno_url = "0.164"
deno_net = "0.156"
deno_web = "0.195"
deno_fetch = "0.188"
deno_crypto = "0.178"
deno_canvas = "0.33.0"
deno_webgpu = "0.131"
deno_websocket = "0.169"
lightning-workspace-hack.workspace = true

[dev-dependencies]
lightning-schema = { path = "../../core/schema" }

[build-dependencies]
serde.workspace = true
serde_json.workspace = true
base64 = "0.22"
hex = "0.4"
deno_core = "0.301"
deno_webidl = "0.164"
deno_console = "0.164"
deno_url = "0.164"
deno_net = "0.156"
deno_web = "0.195"
deno_fetch = "0.188"
deno_crypto = "0.178"
deno_canvas = "0.33.0"
deno_webgpu = "0.131"
deno_websocket = "0.169"

[[bin]]
name = "fn-service-1"
path = "src/bin.rs"
